### ISSUE TITLE
How to get it working with Jest?

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#104]
It seems to be failing on this line in the module index: 
`export { jsonapiModule, utils } from "./src/jsonapi-vuex"; `
full error:
```
./node_modules/jsonapi-vuex/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { jsonapiModule, utils } from './src/jsonapi-vuex'
```
and my .babelrc looks like this:
```
{
  "plugins": ["@babel/plugin-syntax-dynamic-import"],
  "env": {
    "test": {
      "plugins": ["dynamic-import-node", "@babel/plugin-proposal-optional-chaining"],
      "presets": [
        [
          "@babel/preset-env",
          {
            "modules": "commonjs",
            "targets": {
              "node": "current"
            }
          }
        ]
      ]
    }
  }
}
```
Not sure if this is a jest config issue or something that can be addressed by modifying the way exports are done in this code-base? Either way if you have any info on how to get this working I'm sure it will benefit others.

**Comment by mrichar1** [comment]
This looks suspiciously like a Babel issue with transpiling.

I've not used jest at all, but there do seem to be some long discussions on similar issues described here: https://github.com/facebook/jest/issues/6229

It looks like jest doesn't handle `.babelrc` and it needs to become `babel.config.js` (and get refactored).

Can you have a look at this and see if it helps?

Otherwise you'll need to send me your full jest config/package.json etc (or link me to the failing project to clone) so I can test and try to replicate/solve this issue.

**Comment by geoidesic** [comment]
Ok thanks for the reply. I've published the project here: https://github.com/geoidesic/quasar-jsonapi-vuex-jest

To see the issue with jest...
1. cd into project folder
2. then run `yarn install`
3. then run `npm run test:unit`.

**Comment by mrichar1** [comment]
It looks like you need to add `jsonapi-vuex` to the `transformIgnorePatterns setting in `jest.config.js`:

The following gets things working for me in your test repo:

```
transformIgnorePatterns: [
    '<rootDir>/node_modules/(?!(quasar/lang|jsonapi-vuex))'
  ],
```

**Comment by geoidesic** [comment]
I had tried that but was doing it wrong. I did this (which doesn't work):

```
  transformIgnorePatterns: [
    "<rootDir>/node_modules/(?!quasar/lang)",
    "<rootDir>/node_modules/(?!jsonapi-vuex)"
  ],
```
