### ISSUE TITLE
Unclear jv/patch usage

### ISSUE THREAD

**Issue by mitsion** [mrichar1/jsonapi-vuex#106]
Hi,

I'm having issues trying to update entry using `jv/patch`. The problem is that the modified data is being sent as object with the modified attributes in the body of the request instead of the attributes (which always has the unchanged data).

There's no example for the patch method so it's unclear to me if I should commit (`this.$store.commit('setLoading', {})`) the changed data or directly dispatch it (`this.$store.dispatch('jv/patch', {})`).

I've also tried the `replaceRecords` mutation but got an error. 

Could you please update the docs to make it clear on how to use the `jv/patch` and mutations.

Thank you a great lib!

**Comment by mrichar1** [comment]
Hi,

I'll look at updating the documentation to include a patch example, but it basically takes the same syntax as POST - that is a restructured object representing the object to be patched.

For example, say you had `widgets/1` in the API which had the attribute `color: red` you could change this by doing:

```
# Make a new patch from scratch
const widget1 = {
  widgets: {
    1: {
      color: "blue"
    }
  }
}

# OR... get the record from the API and modify it:
const widget1 = await this.$store.dispatch('jv/get', "widgets/1")
widget1.color = "blue"

this.$store.dispatch('jv/patch', widget1)
```

Mutations only affect the local store, and will cause it to then be 'out of sync' with the remote API, so are only usually used internally, or called directly in special cases. I'm not sure where `this.$store.commit('setLoading', {})` comes from though, since there's no mutation with this name in the code!
