### ISSUE TITLE
Add possibility not to use client-generated ID.

### ISSUE THREAD

**Issue by SamGold05** [mrichar1/jsonapi-vuex#11]
I got undefined key in the store when I make an action without Id, because i receive it from the server. Maybe it would be better to get id from response and commit it to the store?

**Comment by mrichar1** [comment]
Hi - thanks for opening this issue!

I have a fix for the `post` method in my local development branch, after I spotted and fixed a similar situation with `patch`. However I've been sidetracked with some other 'pass by reference' bugs I'm looking to iron out, so I haven't yet pushed this.

From the jsonapi spec, if the api response has status `201` then the `post` data didn't contain an `id`, and so the response data will be used. Otherwise, if it returns a `204` (with no data) then the `post` must have contained an `id` and so the `post` data will be used.

I'm hoping to get an update pushed in the next couple of days to fix this and some other bugs - will update this issue when I release a new version.

**Comment by mrichar1** [comment]
Hopefully this update will fix your issue - as described above the code will now use the response from the server if one is provided, and only try to use the client-side data if no server response is given.

Please let me know if this fixes the issue!

**Comment by SamGold05** [comment]
Hi man! Thanks for a great job. You resolved the issue.
