### ISSUE TITLE
README link to Utility Functions docs is dead

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#111]
The link in this section points to a 404: https://github.com/mrichar1/jsonapi-vuex#utility-functions

**Comment by mrichar1** [comment]
I can't seem to reproduce this - both that link, and the JSDoc readme (https://mrichar1.github.io/jsonapi-vuex/#utility-functions) seem to be working fine this morning.

Let me know if you're still seeing the problem?

**Comment by geoidesic** [comment]
Yes, still erring.
<img width="984" alt="Screenshot 2019-11-21 at 11 48 27" src="https://user-images.githubusercontent.com/4637995/69326695-e8c17480-0c54-11ea-96fa-bf6e87df90f1.png">
The screenshot shows the link. The link points to this url: https://github.com/mrichar1/jsonapi-vuex/blob/master/module-jsonapi-vuex.utils.html which gives me a 404.

**Comment by mrichar1** [comment]
Ah, sorry, I thought you meant the link *to* that section was dead - not the API Reference link inside it.

Yes, I see the issue - the API reference links work when you view the JSDocs (i.e. https://mrichar1.github.io/jsonapi-vuex/#utility-functions) but don't when viewing README.md 'directly' on github's project page. I'll see if I can fix them to be absolute links to the docs page, rather than relative links which break.
