### ISSUE TITLE
Add example for fetching meta data

### ISSUE THREAD

**Issue by ruudboon** [mrichar1/jsonapi-vuex#122]
FIrst of all thank you for this library! Works really cool.
I'm getting back a data set from my endpoint and on the root level there are` meta` and `link` tags.
How do I retrieve those (I think with the helpers...)? 
I couldn't figure it out from the documentation. Could you add some example for that?
Would like to display the total number of records etc.

**Comment by mrichar1** [comment]
The usual way to get this is to use the `preserveJSON` config option described here: 

https://github.com/mrichar1/jsonapi-vuex#configuration

This provides the original JSON response in `_jv` under a `json` key in the result from GET/POST etc.

So with it enabled you could do the following to get the object root:

```
this.$store
  .dispatch('jv/get', 'widget/1')
  .then((data) => {
    console.log(data['_jv']['json'])
  })
```

**Comment by ruudboon** [comment]
@mrichar1 Ah I see. I was expecting to find this in the store as well. Thnx.

**Comment by mrichar1** [comment]
The meta and links data in the root is usually related to the request, rather than the resulting data (which has it's own links/meta sections). As such it wasn't obvious where to put it in the store, or how to manage it when there could be multiple asynchronous API requests all happening at once.

Saying that if there's a specific use case you can describe where it would make sense for the root metadata to persist, then I could have a think about how this could be implemented.

**Comment by ruudboon** [comment]
@mrichar1  I think the pagination is one of the best examples in this case. When you fire a query with a limit of x results and you would like to paginate this you would like to know the number of pages so you can create a paginator.

https://jsonapi.org/examples/#pagination

Currently using this in combination with a [datatable](https://vuetifyjs.com/en/components/data-tables#external-pagination) I bind the data from the store to the table and need the meta data for setting up the pagination.
