### ISSUE TITLE
How to create a computed getter for namespaces stores?

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#135]
Hi,

I've tried this https://github.com/mrichar1/jsonapi-vuex#getters
Like so:
```
...mapGetters({
        devices: "devices/get"
      })
```
This gives me a function and not a value.

I tried this:
```
 ...mapGetters({
        devices: "devices/jv/get"
      })
```
Which is undefined. 

I also tried seeing what getters exist:
```
console.log(this.$store.getters);
```
outputs:
```
devices/get: (...)
devices/getRelated: (...)
```

... so nothing like 'jv/get' in there. Also if I map these I get a function not a value. I think the point of a getter is that it's supposed to return a value when called as a value without having to call it as a function.

**Comment by mrichar1** [comment]
There are 2 styles of getter - property-style access and method-style access. jsonapi-vuex relies entirely on the latter, which is why you can pass arguments to them to request parts of the store: https://vuex.vuejs.org/guide/getters.html#method-style-access

The example use of `mapGetters` here is purely to re-map the getter name to a different alias - in your case `devices`. You must still use it as a function, not a simple property, e.g.:

```
<div>{{ devices('foo/1') }}</div>

... or ...

this.devices('foo/1')
```

jsonapi-vuex is used as a module - this means that it has to be loaded into a particular namespace, which appears before the `/`.

The value used is the key used when adding the module to the store. In the docs we use `jv` everywhere (resulting in `jv/get` etc), but in your case I assume you are using `devices` instead of `jv`, e.g.:

```
export default new Vuex.Store({
  strict: true,
  modules: {
    devices: jsonapiModule(api, config),
  },
}
```

So if you want to use `mapGetters` to create an alias for `devices/get` called `devices` you should do:

```
...mapGetters({
  devices: "devices/get"
})

If you want to use property-style getters in your code, then you can create your own getters in the store, and have them make 'static' calls to the jsonapi-vuex method-style getters. Something like:

```
const getters = {
  getItem1: (state, getters) => {
    return getters['devices/get']('item/1')
  }
  
export default new Vuex.Store({
  strict: true,
  getters: getters,
  modules: {
    devices: jsonapiModule(api, config),
  },
}
```

**Comment by geoidesic** [comment]
I can't get this to work at all. Please see https://github.com/mrichar1/jsonapi-vuex/issues/137

**Comment by mrichar1** [comment]
I'm seeing a lot of odd errors in those sandboxes, which look like codesandbox isn't handling some of the ES6 stuff properly. This makes it difficult to work out where errors are coming from.

You might be better off making a standalone repo with the example code in and pushing that to github so I can clone it and run the code locally...

**Comment by geoidesic** [comment]
Or maybe you have instructions for getting the example app in your repo to work? There's no instructions, wasn't sure how to run it.

**Comment by mrichar1** [comment]
The instructions are at the end of the docs in the [Development](https://mrichar1.github.io/jsonapi-vuex/#development) section.

You should be able to just do:

```
git clone https://github.com/mrichar1/jsonapi-vuex
cd jsonapi-vuex
yarn
yarn testapp
```

**Comment by geoidesic** [comment]
Ok here is the branch demonstrating the problem:
https://github.com/geoidesic/jsonapi-vuex/tree/broken-getter

View console log once running. Notice the error:
`this.$store.getters.devices/get is not a function`

**Comment by geoidesic** [comment]
Any chance you could have a look? (I'm dying here, professionally speaking).

**Comment by mrichar1** [comment]
Yep - it's on my todo for today :+1:

**Comment by mrichar1** [comment]
OK having had a quick look ~I think that `_.merge` might be the wrong tool here.

The merge docs say:

> _.merge(object, [sources])
> This method ... recursively merges own and inherited enumerable string keyed properties of source objects *into* the destination object.
> *Note:* This method mutates object.

This means that in your code any properties in `devices` will overwrite those in `jvModule`. Since they both have top-level `actions` and `getters`, both of which have a single function as the value, it gets replaced and the jsonapi-vuex methods 'disappear'.

I think that given these are namespaced modules, the correct approach would be to do:

```
export default new Vuex.Store({
  strict: true,
  modules: {
    devices: devices,
    jv: jsonapiModule(api, { clearOnUpdate: true }),
   },
})
```

then access the methods as `jv/get` and `devices/someGetter` as required.


```

**Comment by geoidesic** [comment]
Hmm.. No. I still don't understand. I've made a commit as you suggest but while I don't get the same error any longer, the getter returns empty even though state is not empty.

**Comment by mrichar1** [comment]
I'm not sure what you expect to happen here:

https://github.com/geoidesic/jsonapi-vuex/blob/323bec87cfa662e29cf2e31756a8ac7a2bb8b41e/examples/testapp/src/components/TestComponent.vue#L20

You don't seem to be making any `action` calls to populate the `jsonapi-vuex` store, and even if you did, axios is configured to connect to the `fakeapiserver` listening at `localhost:3000` which returns data from `testapp.json`. This fake data has no `devices` endpoints so would just return a `404`.

**Comment by geoidesic** [comment]
The README here: https://github.com/mrichar1/jsonapi-vuex#get states: `Get returns information directly from the store for previously cached records.`

Since I'm populating the store's state manually:
```
export default function() {
  return {
    devices: [
      {
        name: 'asdf',
      },
      {
        name: 'qwer',
      },
    ],
  }
}
```
... my expectation is that this would be read as 'cached` data which is returned directly from the store, since it is available.

**Comment by mrichar1** [comment]
Ahh - no each module has it's own independent state. You're populating the state in the `devices` module - so `jv/get` will still see an empty store.

You can use `rootState` if you need to access shared/global state, or you might be able to hack it so that they both reference the same state object, but that's outside the usual use-case for modular stores.

I'd recommend having a read of all the Vuex docs, especially the section on `modules` to get an understanding of how these parts all fit together: https://vuex.vuejs.org/guide/modules.html

**Comment by geoidesic** [comment]
Ok but that's highly confusing then... I mean the idea of a module is that it stores its own state. 

Now we're ending up with the devices module having its state split out over two different modules – which means that none of the getters or setters I write in the devices module will be able to access those created by the jsonapiModule unless I get tangled up in roostate and such.

If that is the case then this library has extremely limited use because one can't extend it in any way at all. 

It's so confusing, especially as I actually had this working a few weeks ago using lodash merge and now it's not working. Can't see why.

**Comment by mrichar1** [comment]
OK - so most projects most of the time want separate namespaces for vuex modules, to avoid problems with name collisions, race conditions etc. Given you'd set up namespaced modules, the `merge` didn't make sense so I was giving you help to go back to 'pure' namespaced separation.

If however you know that you *do* want to have a single global store which all vuex modules share, then just don't use `namespaced: true` in any of the modules and they will all share the same global state.

At the moment `jsonapi-vuex` always sets `namespaced: true`. I _think_ be able to work around it by doing:

```
const jvMod = jsonapiModule(api, {})
jvMod.namespaced = false

export default new Vuex.Store({
  strict: true,
  modules: {
    devices,
    jvMod,
   },
})
```

**Comment by geoidesic** [comment]
No I definitely DO want namespaces vuex modules. What I'm saying is that I don't see how those can co-exist with this library.

I mean for example. I have `devices` as table on the back-end db. This gets served as a JSONAPI model. I want jsonapi-vuex to consume that but I also want to be able to write my own mutations, actions and getters for that namespaces module.

From the thread above, that doesn't seem to be possible.

**Comment by mrichar1** [comment]
Ahh - i understand now! I should probably just have asked at the start what the end goal was, so as to not cause all the extra confusion!

This should be doable... Instead of trying to merge whole modules, you need to do it for each property - `action`, `getter`, `mutation` and `state`. These exist just as objects where the key is the method name, and the value the function, so it's easy to extend/override them:

```
const myAction = function() { ... }

const jvMod = jsonapiModule(api, {})
jvMod.actions['myAction'] =  myAction
```

It *should* actually be possible to use `merge` here, provided you're careful that the 'new' object's keys are different to those in jsonapi-vuex (unless you want to replace them of course!)

```
const myActions = {
  myAction1: function() { ... },
  myAction2: function() { ... },
}

_.merge(jvMod.actions, myActions)
```

Let me know if that helps!

**Comment by geoidesic** [comment]
Lodash merge seems to work if I reverse the arguments. I'll close once I've confirmed.

**Comment by geoidesic** [comment]
It's most peculiar. From your explanation above about `_.merge`'s behaviour it shouldn't work at all. However, reversing the order of the arguments passed to `_.merge` **does** work on my actual project. However it **does not** not work on the example branch.

**Comment by geoidesic** [comment]
Confirmed. I've committed to the branch and also here is a codesandbox demonstrating: https://codesandbox.io/s/jsonapi-vuex-example-uck1m

**Comment by geoidesic** [comment]
UPDATE: `_.merge` even with reversed arguments causes other problems: https://github.com/mrichar1/jsonapi-vuex/issues/139

**Comment by mrichar1** [comment]
As I explained previously `_merge` should only be used with the individual properties of the Vuex modules - *NOT* with the whole modules.

I definitely wouldn't try to use it this way, and would expect _bad things_™ to happen if you do.

**Comment by geoidesic** [comment]
I've tried it with individual properties and  _bad things ™_ still happen.

E.g. 
```
let jvm = jsonapiModule(api, {});
let queuetest = {
  namespaced: queue.namespaced,
  state: _.merge(jvm.state, queue.state),
  actions: _.merge(jvm.actions, queue.actions),
  getters: _.merge(jvm.getters, queue.getters),
  mutations: _.merge(jvm.mutations, queue.mutations)
};
```
 I've pinned it down to the getters. It seems that what's happening is nothing to do with the order of the arguments to `_.merge`  (that was coincidental). It is to do with the fact that the getters are executed or unwrapped by the merge.

So e.g. if I have a getter written like this:
```
export const oinkyPoinky = state => state.messages;
```
Then that getter will be undefined.
However if I wrap it in a function like so:
```
export const oinkyPoinky = state => () => state.messages;
```
Then it will work.

I don't fully understand why this happens however. It only seems to happen with getters.

**Comment by mrichar1** [comment]
You're not doing quite what I suggested there. You're not adding new methods to the existing module - you're trying to combine methods from 2 existing namespaced modules and add them to the 'root' namespace. I strongly suspect that won't work, even if the merging isn't the issue.

Please try the simple example I gave above of adding a single new method (action, getter etc) to the instantiated `jsonapi-vuex` module and see if that works as expected. Something like the following:

```
// A 'dumb' getter that returns the whole state
const getAll = (state) => state

const jvMod = jsonapiModule(api, {})
jvMod.getters['getAll'] =  getAll

export default new Vuex.Store({
  strict: true,
  modules: {
    devices,
    jvMod,
   },
})

this.$store.getters['jv/getAll']

```

If that works then there are probably better ways to add mutiple getters at once than using `_.merge` . getters aren't simple objects - they contain functions, JS getters etc that I suspect `_.merge` isn't capable of playing nicely with.

**Comment by geoidesic** [comment]
Ok sure. I mean that works of course. I just don't see how it helps me?

**Comment by geoidesic** [comment]
Hmm.. actually no I assumed that would work but I can't get it to work.

**Comment by geoidesic** [comment]
So it's not merge breaking things then, it's `new Vuex.Store`.
This doesn't work:
```
const jvMod = jsonapiModule(api, {});
const getMessages = state => state.messages;
jvMod.getters["getMessages"] = getMessages;
const.config = {
  modules: {
    jvMod
  }
}
const store = new Vuex.Store(storeConfig);
console.log(store.getters['jvMod/getMessages]); // undefined
```
This does work:

```
const jvMod = jsonapiModule(api, {});
const getMessages = state => () => state.messages;  //NB: the wrapper
jvMod.getters["getMessages"] = getMessages;
const.config = {
  modules: {
    jvMod
  }
}
const store = new Vuex.Store(storeConfig);
console.log(store.getters['jvMod/getMessages]); // undefined
```

Once again it only seems to work if the function is wrapped.

**Comment by mrichar1** [comment]
It works as expected for me.

Do you have a `messages` property in `state`? I'm guessing this is why you see `undefined`.

In the second example, the getter returns a function, so that is what you get back when you log it. If you actually called the function - e.g.  `store.getters('jvMod/getMessages']()` - you'd again get `undefined`.

**Comment by geoidesic** [comment]
I do have a `messages` property in `state`. Why would that be bad?

**Comment by mrichar1** [comment]
I was assuming that either `state` had no `messages` property, or the value of `messages` is `undefined` ?

**Comment by geoidesic** [comment]
No.
```
export default function() {
  return {
    messages: []
  };
}
```

**Comment by geoidesic** [comment]
Well actually that's in another module now.

**Comment by geoidesic** [comment]
Ok.. so before I lose the thread. How does this help our cause? :)

**Comment by mrichar1** [comment]
Right :-D So with vuex modules you have 3 choices...

1. Set `namespaced: false` - every module shares a 'global' state.
2. Set `namespaced: true` - every module gets it's own state.
3. Set `namespaced: true` but then 'extend' a module to have extra methods.

The latest stuff above is option 3, the others we discussed earlier on in this thread.

In general people use 2 with `jsonapi-vuex`, so that the requests to the API end up in one store, but they can use another state for things like session info, app state etc. But the other options are available.

It all comes down to things like 'how many different modules will you be using?', 'will they need to share state 'directly' (one module can always call another modules getters/actions/mutations), 'will there be property name conflicts if they share a global state etc.

**Comment by geoidesic** [comment]
Ok that makes sense. 

What's a bit confusing for me is that it seems that you are suggesting that there should only ever be one jvModule, which is not clear from the docs. My expectation on reading the docs was that every module in my vuex store could be `converted` into a jvModule, that doing so would simply add the required getters and setters to each module.

**Comment by mrichar1** [comment]
So the aim of the project is that you only have one `jsonapi-vuex` (or at least one per API you want to connect to). It then gives you 'high level' getters and actions, working with normalised data, effectively mirroring your API, but in an easier to consume way.

I'm interested to know what your plans are in terms of multiple modules in the store, and what extra 'high level' actions/getters you envisage needing where the existing ones don't cover your requirements?

**Comment by geoidesic** [comment]
I don't know that there is a need. Now that I understand your angle, it's possible that I've just been approaching it from the wrong end. I'll give it some thought and will let you know if I come to that need.

**Comment by geoidesic** [comment]
Here's an example of where I need an extra mutation for the store:
```
// store/queue/mutations.js
[types.QUEUE_ADD_MESSAGE](state, message) {
    if (!getters.hashExists(state)(message.hash)) {
      state.messages.push(message);
    }
  }
```
So now the problem I have is that state.messages is not where `jv` is storing messages. Since this involves logic that is required to run against the message state, I can't put this code here. It then has to be attached to the jvModule instead as a mutation I guess?
