### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by stefanvanherwijnen** [mrichar1/jsonapi-vuex#147]
Hi,

Do you have any plans on switching to TypeScript in the future?

I am currently adding the missing types manually in my project, which I could PR into a typings definition when finished. But ideally the package is written in typescript and the types are added in the code.

**Comment by mrichar1** [comment]
Hi,

I hadn't thought of changing the project to typescript at this point - mostly because I have no experience of typescript to know what would be the correct approach, benefits etc. 

I notice that Vue 3 has switched over to typescript, so it is something I'd like to look into at some point - and would be happy to consider any PRs etc related to switching over - though there are some outstanding feature request issues which are probably more pressing at this point (the large test suite at least goes some way to offsetting the easy-to-make JS mistakes!)

**Comment by stefanvanherwijnen** [comment]
Functionality wise there would be no difference between TS and JS, but TS does provide a better development experience imo (https://code.visualstudio.com/docs/languages/typescript).

The biggest upside as well as downside is that it won't let you write 'bad' code in `strict` mode. If you assign a string to a number somewhere deep in your code which will normally never be used, it won't compile. In the same way you cannot use JS packages without type declarations, and if a type declaration is incorrect you will also end up with compilation errors.

I'd indeed recommend looking into typescript. I'll PR the type declarations when I've finished them so the JS package can be used in TS, but as I do not know the ins and outs of this package some error might sneak in and that would basically make them useless (that's why it would be better to define the types in the code of the package itself).

Imo the migration should be performed by the package maintainer, but I'd be happy to help out once you get to it.
(I believe typescript support in Vuex is also not 100% either, so it will have to wait on that first)

**Comment by Tscheffrey** [comment]
Hi @stefanvanherwijnen,

Did you succeed in adding the missing type definitions?
If yes, could you make a PR or add least make them available for everyone to use?

**Comment by stefanvanherwijnen** [comment]
I actually wrote my own implementation, but have stopped using JSON API beforeI could use it: https://github.com/simsustech/jsonapi-store

I started using Vue 3 before Vuex was supported, hence the reason for this approach.

I also believe that due to the store structure and use of Proxy it might be cumbersome to correctly add the types afterwards (I.e. it is better to rewrite in TS).

**Comment by mrichar1** [comment]
`jsonapi-vuex` has now been updated for Vue3 support - though in reality that required very little changes.

There is a bigger question about whether there should be a 'low-level' Vue3 rewrite, since we now have the option to use Typescript, Proxies and/or the Composition API.

However the code 'just works' at the moment, so this isn't a high priority, and while typescript would be nice, we have a large test suite that helps keep us straight.

I won't (re)open issues for the above, as they're likely to just go stale unless/until there is motivation to implement these things. (Though always happy for contributions!)
