### ISSUE TITLE
Intended use

### ISSUE THREAD

**Issue by quantavi** [mrichar1/jsonapi-vuex#148]
I went through documentation, but unfortunately I did find an example that would suit our scenario.

Basically, what we want to do is to:
1. get the Book collection from API
2. display the collection from store via let's say Vuetify v-data-table
3. Modify/Add Authors that are related to Book
4. save changes to the API 

Here is how we do it currently:
1. get the Book collection from API
```
this.rawBooks = await this.$store.dispatch("jv/get", [
      "/api/v1/books",
      {
        params: {
          include: "authors",
        },
      },
    ]);
```
First we do request. Works fine.
```
    this.books = Object.values(this.rawBooks).map((book) => ({
      book_number: book.book_number,
      title: book.title,
      authors: Object.values(book.authors).map(
        (author) => author.first_name + " " + author.last_name
      ),
      _jv: book._jv,
    }));
```
Then we are transforming the data, so that v-data-table can display it and also because we had problems with store complaining about mutating the data outside of the store.
We need to do it, otherwise table has problem processing the author data, as 
it looks like: 
```
authors: Array (2)
0 {__ob__: Observer, …}
1 {__ob__: Observer, …}
```
and the table has to have specific prefix to find for example "first_name"

2. The preprocessed data displays fine, but now comes the hard part - how to save the modified data.
It is not original data anymore as it was preprocessed. Maybe we shouldn't preprocess it and work on original data?
However modifying original data means that modifying data outside the store and removing the STRICT mode, which is not desired. 

3. OK, so we have both original data and preprocessed data, but how do we add to any of those additional author that will be saved to API?
We are using this code to update data to save to API, but we don't know how to prepare **this.editedItem** for this operation? 
```
await this.$store.dispatch('jv/patch', [this.editedItem, { url: '/api/v1/books/'+this.editedItem._jv.id }]);
```

Wondering if anyone knows how to achieve top 4 points in elegant manner?
How to work efficiently on relations and how to avoid modifying store data outside of mutations?
Thanks

**Comment by mrichar1** [comment]
Yes, the key point is not to work on the original data.

My usual model for this kind of work is something like the following (using [PrimeVue DataTable](https://www.primefaces.org/primevue/showcase/#/datatable), but it should work for anything where you can use separate `v-bind` and `@event` instead of `v-model`):

I start by fetching the data (`this.$store.dispatch('jv/get')`) and then convert this to an array of objects (which is what `DataTable` consumes) using `Object.values` - more or less what you're doing:
```
<DataTable  
  :value="dataArray"
  @row-select="onRowSelect"
/>
```
At this point nothing should have tried to modify `dataArray`.

When a table row is selected, this calls the `onRowSelect` function, passing over the data of the selected row (i.e a single object from the  array). This function then presents an edit dialog with all the data presented as input fields.

The important part is that the edit dialog also uses `v-bind` and a custom method on the `@input` event, *not* `v-model`. Something like:

```
<div>
 <!-- key = author, title etc -->
  <div v-for="(value, key) in rowData">
    <InputText
      : value="value"
      @input="onInput(key, $event)"
    />
  </div>
  <button
          type="submit"
          @click="updateAPI()"
  >
</div>

methods: {
  onInput (key, value) {
    this.newObject[key] = value
  }
}
```


So the initial value is the original one, but `onInput()` writes the modified key:value to a *new* object.

The 'save' button on the dialog calls a method which gets passed both the `rawData` object, and the new object. It can then diff them, do validation on the new values, decide if it's a POST/PATCH, and call the appropriate action.

Obviously there are lots of variations - the `updateAPI()` logic could be put inside `onInput` (if you want real-time API updates, rather than a save button). Validation etc can also be done in `onInput()` by passing in `value` as well (as long as you don't modify it!).

I hope that makes sense - it probably isn't the only approach that solves this problem, but it's the one I've settled on and it seems to work well for my use cases. Let me know if anything isn't clear and I'll try to offer some more examples!

**Comment by quantavi** [comment]
@mrichar1 Thanks!

However ... :)

So, I have raw data and processed data for v-data-table.

On row edit I take the id of row and also make copy of the edited object so I modify only local object.
```
this.editedIndex = this.rawBooks.indexOf(item);
this.editedItem = Object.assign({}, item);
```
While saving, I am finding object in the raw data using id. So far, so good. 
Now I make a copy of the raw object and then I assign edited values like title, number, etc. to the copied object.
I have changed the title to **"A Glass of Blessings 2"**
```
var obj = Object.assign({}, this.rawBooks[this.editedIndex]); // <- I suspect this could be copying too much or too little ;)
obj.title = this.editedItem.title; // <- Here the obj.title is assigned "A Glass of Blessings 2" title
obj.book_number = this.editedItem.book_number;
```
I am now doing console.log of the copied object(obj) -> all modifications are there.
Then I am dispatching the change and I can see that the request goes to server **with unmodified data**.
```
 await this.$store.dispatch('jv/patch', [obj, { url: '/api/v1/books/'+obj._jv.id }]);
```
```
{
   "data":{
      "id":"2",
      "type":"books",
      "relationships":{
         "editions":{
            "links":{
               "related":"/api/v1/editions?filter[book_id]=2"
            }
         },
         "authors":{
            "links":{
               "related":"/api/v1/beneficiaries?filter[book_id]=2"
            },
            "data":[
               {
                  "type":"beneficiaries",
                  "id":"61"
               },
               {
                  "type":"beneficiaries",
                  "id":"70"
               }
            ]
         }
      },
      "attributes":{
         "title":"A Glass of Blessings",
         "book_number":"a147e57c26ef9b406045b1362c7cdf80"
      }
   }
}
```

Any ideas why? 

Also, how would I add authors to the book? Do I only need to add  ids and type if authors are already in DB? 

Lastly, in your example you are using: this.newObject. Is this object built from the ground? Or made by some copying mechanism?

**Comment by mrichar1** [comment]
So I'm not sure why `obj` doesn't contain the modified data in the dispatch - maybe a race condition with async methods somewhere?

My `this.newObject` is really just `{ _jv: { type: type } }`. This is enough for a new item (POST), but if I'm modifying an existing object (PATCH), then it also gets `id` added.

The main thing is that the `jsonapi` spec requires a `patch` to only contain things which have changed, so I don't do anything to copy the original object. There are 3 risks with copying:

1. attributes can be nested, but `Object.assign` is a shallow copy, so any nested attribute would be a reference to the original object, and would mean edits would be dangerous.

2. Copies can be slow and/or use up resource - especially if you have nested or large objects.

3. Imagine you fetch the object from the API and your local 'cache' in the store has `book_price: $1.99`. Afterwards someone else modifies the price on the server so it's now `$100.00`. If your patch contains `book_price` then you will change it back, even though you only meant to modify `title` or `book_number`.

I'd try making your `obj` a 'stub' object like my `newObject` above, and just modify it directly, rather than trying to copy the original object. this may well solve the 'unmodified data' problem, and will prevent any of the issues listed above.

In terms of adding authors, assuming they exist in the DB then you just need to update the relationships section. the easiest way to do this is by creating/updating  `_jv.relationships.data` in your new object (this is one place where a copy may be necessary from the original object). Note there are plans to make it possible to modify relationships 'directly', but this feature isn't in yet: #88

**Comment by quantavi** [comment]
@mrichar1 Thank you. I will try your tips and report back.

**Comment by quantavi** [comment]
@mrichar1 Thank! I got most of it working. Just a final question. How could I remove a relationship?
I am updating the record, potentially modifying attributes, but I want to modify the relationships too.
Currently the PUT request looks like this:
```JSON
{
    "data": {
        "id": "66",
        "type": "books",
        "relationships": {
            "authors": {
                "data": [
                    {
                        "type": "beneficiaries",
                        "id": "3"
                    },
                    {
                        "id": "32",
                        "type": "beneficiaries"
                    },
                    {
                        "id": "38",
                        "type": "beneficiaries"
                    }
                ]
            }
        },
        "attributes": {
            "title": "A Glass of Blessings",
            "book_number": "b1ae4ca3239be8586811508359211ed7"
        }
    }
}
```

How would I remove beneficiary 3 for example? Is it possible to do it in one request?

**Comment by mrichar1** [comment]
The spec is here:

**Comment by quantavi** [comment]
@mrichar1 Thank you. 
On the backend we use Rails + Graphiti (https://www.graphiti.dev/) and they support something called method. I am not sure if that is part of vanilla JSON-API. 
So in our case, I can generate such JSON: 
```JSON
{
    "data": {
        "id": "66",
        "type": "books",
        "relationships": {
            "authors": {
                "data": [
                    {
                        "type": "beneficiaries",
                        "id": "3",
                        "method": "disassociate"
                    },
                    {
                        "id": "32",
                        "type": "beneficiaries"
                    },
                    {
                        "id": "38",
                        "type": "beneficiaries"
                    }
                ]
            }
        },
        "attributes": {
            "title": "A Glass of Blessings",
            "book_number": "b1ae4ca3239be8586811508359211ed7"
        }
    }
}
```

Which removes the association to beneficiary 3 correctly.

Thanks again for help!
