### ISSUE TITLE
"meta" is not recording

### ISSUE THREAD

**Issue by SamGold05** [mrichar1/jsonapi-vuex#15]
There is no "meta" in response, if it placed in the root of the object.
JSONAPI record look like this, for example:
```
{
  "meta": {
    "totalPages": 13
  },
  "data": [
    {
      "type": "articles",
      "id": "3",
      "attributes": {
        "title": "JSON:API paints my bikeshed!",
        "body": "The shortest article. Ever.",
        "created": "2015-05-22T14:56:29.000Z",
        "updated": "2015-05-22T14:56:28.000Z"
      }
    }
  ]
}
```

**Comment by mrichar1** [comment]
Hi - thanks for raising this.

Can you provide more info as to what you are hoping to achieve with `meta` here, and what actions/methods you are using to do so?

In `GET` it's difficult to do much with top-level `meta`, due to the difficulty of matching up e.g. top-level `meta` to the individual records post-normalisation - that is, the `meta` info may relate to a specific request or collection, but the stored normalised data does not have this context. It would be possible to have the top-level keys attached to the immediate response json from the method call, if this was useful?

It should be possible to allow the addition of top-level keys in the json that forms the request (i.e. POST/PATCH/DELETE and the request part of GET). This would allow the addition of session-specific info in the meta section (e.g. for things like authentication tokens etc). I expect the easiest way to accomplish this would be to allow the methods to take a jsonapi 'template' and do a merge of the `data` key before sending to the API server.

**Comment by mrichar1** [comment]
I've implemented some changes which will hopefully go some way to resolving this issue.

There is now a `preserve_json` config option in jsonapi-vuex (which defaults to `false`). If set to `true`, then the return value for all `actions` contains the jsonapi response from the server (minus the `data` section, to avoid duplication) under a `json` key in the `_jv` part. (obviously this won't be transferred into the store, it is only in the return value for immediate use).

As to the question of manipulating the jsonapi data in the request, having looked into it I think this should be done in `axios` using the `transformRequest` and `transformResponse` hooks (which can be passed in per-session (using an `axios instance` as is done for headers in the example in the docs), or per-request (using an `axios config object` passed in to `dispatch`.

Let me know if you think this is enough for your needs. I've released as 0.0.14

**Comment by SamGold05** [comment]
Thanks for quick response. 
I need "meta" for using pagination.
I think there are more elegant solution. Maybe normalized data place into "data", meta into "meta" and etc. Something like this:
```
{
  "meta": {
    "totalPages": 3
  },
  "data": {
    ...normalized_data
  }
}
```

**Comment by mrichar1** [comment]
Hi,

The main aim of normalisation was to simplify access to attributes, which is why attributes are top-level, and everything else goes under `_jv`. So attributes are accessed as: `widgets.1.color` and `meta` ends up as: `widgets.1._jv.json.meta` (similar to: `widgets.1._jv.rels`)

The reason that there is an extra `json` key is that an item may have `meta` information, and there is a risk of collisions between top-level and item-specific `meta` information if they both go directly in `_jv`.

So the design decisions are based on the general case use of jsonapi - of course if you know that you won't hit these issues or collisions, its easy to modify the records, either using the axios `transform` hooks, or just in the code after receiving the response.
