### ISSUE TITLE
Webpack - Failed to compile Error

### ISSUE THREAD

**Issue by alericoj10** [mrichar1/jsonapi-vuex#167]
> ./node_modules/jsonapi-vuex/src/lib.js
> Module parse failed: Unexpected token (389:24)
> You may need an appropriate loader to handle this file type.
> |     const norm = Object.assign({ [this.jvtag]: data }, data['attributes'])
> |     // Create a new object omitting attributes
> |     const { attributes, ...normNoAttrs } = norm[this.jvtag] // eslint-disable-line no-unused-vars
> |     norm[this.jvtag] = normNoAttrs
> |     return norm

I got it working by doing the following:
`// Create a new object omitting attributes`
`delete norm['attributes']`
`return norm`

**Comment by mrichar1** [comment]
This looks suspiciously like a Webpack/babel error, rather than a problem with the code - I'm guessing the parse error is related to the use of the spread operator (`...normNoAttrs`).

I can only suggest double checking the contents of `vue.config.js` and `babel.config.js`for any issues, and also ensure that all the Vue dependencies (webpack, babel etc) are correctly set up in `package.json`

**Comment by alericoj10** [comment]
Yes,  the problem is that I'm using webpack 3, and it doesn't support ES6 syntax.
Thank you for the quick answer!
