### ISSUE TITLE
Webpack Parse Fail in 0.0.16

### ISSUE THREAD

**Issue by AtlantaJones** [mrichar1/jsonapi-vuex#17]
Got everything set up today, just as in the docs, and when Webpack compiles I'm getting the following error:

![image](https://user-images.githubusercontent.com/2522697/52819176-ac823780-3076-11e9-90a6-e1e9de6cde97.png)

I'm using:

- Vue 2.6.6
- Vuex 3.0.1
- jsonapi-vuex 0.0.16

Pretty sure I'm set up properly, so hoping to get some advice. Thanks.

![image](https://user-images.githubusercontent.com/2522697/52819399-34684180-3077-11e9-819c-40394636d78b.png)

**Comment by mrichar1** [comment]
The issue here is the use of the spread syntax(...) which is in the new es standards but not widely supported.

Vue explicitly uses the spread operator and does so by including Babel to transpile around any issues. You should check your Babel config in .babelrc and/or package.json as explained here: https://forum.vuejs.org/t/vue-loader-unexpected-token-error-for-using-spread-operator-on-my-vue-component/10241/7
