### ISSUE TITLE
TypeError: property "system" is non-configurable and can't be deleted

### ISSUE THREAD

**Issue by ekampp** [mrichar1/jsonapi-vuex#180]
From what I can read in [this issue on stackoverflow](https://stackoverflow.com/questions/29044212/why-is-this-configurable-property-not-deletable), not all properties are deletable even from a configurable object.

I have a JSON:API object that looks like this: 
```json
{
  "data": { ... },
  "relationships": {
    "system": {
      "data": { ... }
    }
  }
```

And I'm getting this error when I try to parse that object from my API: **Uncaught (in promise) TypeError: property "system" is non-configurable and can't be deleted**

Here are the relevant parts of the stack trace from my dev tools:
```
    normToStore lib.js:466
    updateRecords lib.js:532
    replaceRecords mutations.js:50
```

In this case, I believe that the relationship `system` is special to ES somehow, and it refuses to delete it?

**Comment by mrichar1** [comment]
Hi,

Thanks for raising this issue.
Looking at the code I think this is less down to `system` being special, and more that `normToStore` is trying to delete something which is provided by a getter.

The code in `normToStore` is very old - from before `rels` were getters, so I suspect this delete operation probably shouldn't be in the code any more. However I can't be sure as to be honest I'm not 100% sure what the aim of this code is!

The problem is that neither the unit  nor the e2e tests cover this code path, so it's not being tested at all, so I don't know if taking it out will break something.

Could you provide me with some more detail on what you are doing with `jsonapi-vuex` that leads to this error - specifically what Vuex actions/mutations/getters you are calling, a (brief) outline of what your API data looks like etc? That way I can work out how to improve coverage and try to work out what this code is for, and whether it is still needed.

**Comment by ekampp** [comment]
Hi, @mrichar1. 

Thanks for the fast response. I will get back to you with a canonical example that triggers the problem. Until then, turning `followRelationshipsData` off sidesteps the problem. I assume it effectively skips the `normToStore` code.

**Comment by ekampp** [comment]
Ok. The problem hasn't happened for a while. I guess I was doing something wrong when I was trying to build up the `_jv` section. I'm not entirely sure what I changed, but closing this issue now.
