### ISSUE TITLE
Support Undo

### ISSUE THREAD

**Issue by mhluska** [mrichar1/jsonapi-vuex#20]
It would be interesting to see support of undo/redo. Perhaps it is outside of the scope of this library. Currently I am doing this to undo:

```js
methods: {
  completeTodo() {
    const todo = this.todo;

    todo['is-done'] = true;
    this.$store.dispatch('jv/patch', todo);

    this.$toasted.show('Todo complete', {
      action: {
        text: 'Undo',
        onClick: (e, toast) => {
          todo['is-done'] = false;
          this.$store.dispatch('jv/patch', todo);

          toast.goAway(0);
        },
      }
    });
  },
```

In other words, I have to manually describe the opposite of the previous PATCH request and send another PATCH. Would it be feasible to add undo functionality where the vuex mutation is rolled back and the corresponding network request is sent out automatically?

Something like..

```js
this.$store.dispatch('jv/rollback', { steps: 1 });
```

**Comment by mrichar1** [comment]
Undo/redo is an interesting idea, but also potentially quite a complex one to implement.

It would require the store to have a history, storing previous changes to the data, and allowing switching between entries. Not impossible to implement, but would require some thought on structure.

However there are some issues to be worked round, the main one being that *API updates would always need to be preceded by a `get`* or *we need to use transactions*.

1. At its simplest, if your first action is a `patch`, then to 'undo' this you need to know the state of item in the api before that. This means that every `patch` needs a `get` immediately² beforehand, which is inefficient.

2. API actions are racey. Since the get and update operations are separate, the `get` can't really happen immediately before the update, and other actions can happen inbetween. For example:

a. Widget has color red.
b. User A `get`s widget.
c. User A `patch`es widget color to black.
d. User B `patch`es widget color to blue.
e. User A undoes their patch, widget color is red.

This is a general problem with raceyness in RESTful APIs (there are protocols that implement a sort of 'update-if' where an update is sent along with a representation of what the client thinks the data currently looks like, and the server rejects these if it doesn't align - however there's nothing in jsonapi spec for this just now...) However there's a subtle difference between a series of consecutive patches (where you can at least expect 'last one wins') and undo, where there's a difference between 'undo the change I made' and 'put it back to what it was before'. Should widget now be red or blue? People have different opinions on this!

I'll mark this issue as 'enhancement' but also as 'help wanted' as I'd be happy for this to be added, but it needs thinking about and doing well, and I might not have the time to work on such a feature!
