### ISSUE TITLE
Cannot access included records when using api/search

### ISSUE THREAD

**Issue by priessP4U** [mrichar1/jsonapi-vuex#213]
I use the search action for a select2 search/autocomplete field because I don't need any data propagated to the vuex store here, I just pass the results to select2. 

Using the search action I cannot access the _included_ array since this seems to work only if records have been added to the store previously (which is not the case when using search method). The only options for me are a) accessing the original json object to retrieve the included records b) using get action instead of search action or c) making additional AJAX calls to retrieve related data or d) not including any records. 

Is there any other way of retrieving included records when using _search_ action?

**Comment by mrichar1** [comment]
Hi,

You're right that the `search` action doesn't currently have a way to access `included` data in normalised form, and your suggested options are the only ones currently available. This is because `search` is identical to `get` but with mutations disabled. Includes are normalised and committed straight into the store, with the 'main' object then having related props which are references to these stored items.

It would be possible to modify the code such that if enabled, normalised included relationships were added 'directly' to the 'main' object - but this would require a bit of fiddling in the code-base to handle this.

However, usually the 'extra step' of writing the data to the store is trivial compared to the time/effort of processing the included relationships. In these cases there is not much of a performance benefit from using `search` instead of `get`.

If you want the benefit of having the references in the store for includes etc, but also don't want to worry about having stale data then you can use `get` but also enable the config option `clearOnUpdate`. This will drop the contents of the store for a given endpoint when that endpoint is fetched again.

If you have a specific use-case where you can see a ned for `search` to include all related data from includes, and have good reasons not to use `get` (with or without `clearOnUpdate` then do let us know and we can have a look at adding this functionality to `search` at some point (or we're happy to consider a PR if you're up for adding it yourself).

**Comment by priessP4U** [comment]
Ok, thanks a lot for clarifying this!

``` but also don't want to worry about having stale data then you can use get but also enable the config option clearOnUpdate```
Thanks, I will go for that solution I guess.
