### ISSUE TITLE
Multiple loads of same object with different includes should merge relationships

### ISSUE THREAD

**Issue by staaam** [mrichar1/jsonapi-vuex#29]
Currently get of object will fully replace existing instance in the store. This may cause previously loaded relationships being lost. Example:
dispatch: get /article?include=author - will store author and article with rel=[author]
dispatch: get /article?include=comments - will store comments and article with rel=[comments], thus article.authror is not accessible anymore. this can also happen from includes/nested includes, for example:
dispatch get /authors?include=comments
dispatch get /artcles?include=author - will also replace author instance, thus all author comments won't be resolvable through author

I'd propose to improve add_records mutation to merge relationships of existing object from the store and new object.

PS: similar issue may happen when retreiving same object with different fields from different places, which will leave only last loaded fields in the store. Worth considering merging them as well.

**Comment by mrichar1** [comment]
I'm slightly confused by this question...

As far as I can see, if you have a resource with relationships then requesting an include will potentially add extra data to it, but the `relationships` section will always contain all relationships:

> get('article/1')
```
{
  type: 'article',
  id: '1',
  attributes: { ... },
  relationships: {
    author: {
      data: { type: 'author', id: 10 },
    },
    comments: {
      data: { type: 'comments', id: 99 }
    }
  }
}
```


> get('article/1?include=author')
```
{
  type: 'article',
  id: '1',
  attributes: { ... },
  relationships: {
    author: {
      data: { type: author, id: 10 },
    }
     comments: {
       data: { type: 'comments', id: 99 }
    }
  },
included: [
  {
    type: author,
    id: 10,
    ...
  }
}
```

Looking at the code, the `get` action will iterate over each item in `included` and store these.  then `followRelationships` will iterate over *all* `relationships` and populate `x._jv.rels`. 

So after the first `get`:

Store contains:
* `article.1` (added)
* `author.10` (added)

`article.1._jv.rels` contains:
* `author.10`

and after the 2nd get:

Store contains:
* `article.1` (replaced)
* `author.10` (untouched)
* `comment.99` (added)

`article.1._jv.rels` now contains:
* `author.10`
* `comment.99`

Let me know what I'm missing here!

**Comment by staaam** [comment]
You're right, if you assume that id's of related objects are returned regardless of include, which is not a case in many situations. So,
> get('article/1')
```
{
  type: 'article',
  id: '1',
  attributes: { ... },
  relationships: {
    author: {
      "links": {
        "self": "/article/1/relationships/author",
        "related": "/article/1/author"
      }
    },
    comments: {
      "links": {
        "self": "/article/1/relationships/comments",
        "related": "/article/1/comments"
      }
    }
  }
}
```

and data object (with ids) will be included only if requested:
> get('article/1?include=author')
```
{
  type: 'article',
  id: '1',
  attributes: { ... },
  relationships: {
    author: {
      "links": {
        "self": "/article/1/relationships/author",
        "related": "/article/1/author"
      },
      data: { type: author, id: 10 },
    },
    comments: {
      "links": {
        "self": "/article/1/relationships/comments",
        "related": "/article/1/comments"
      }
    }
  }
},
included: [...]
```

Thus in your last example - the store will contain all objects (article.1, author.10 and comments.99) but the articles.relationships will contain only comments ids without author id.

**Comment by mrichar1** [comment]
OK - I read through the jsonapi spec again to see what I was missing.

So my original assumption was correct - `include` has no bearing on `relationships` - specifying (or not) an include should not affect what is contained in `relationships`.

However you are right that an object might not contain all its relationships in (at least) 2 situations.

1 Sparse fields, e.g.: `get('article/1?fields[article]=author` would *only* return the author relationship, and omit all other fields - relationships *and* attributes!

2. Though there's no formal approach described, it is possible to have pagination of relationships, so a response may only contain a subset of all its relationships.

So we're both right! :smiley: 

Since there are pros and cons to both a 'delete/replace' or an 'update' strategy, I reckon the simplest is to make this a toggleable option, and leave it up to the module user to decide which use fits them best.

I'll look at implementing this as `store_update_policy = replace|update` - it should be a trivial `if/else` calling either `add_record` then `remove_record`, or just `update_record`.

We can leave the issue of record expiry, stale caches etc off for now - since the `delete_record` mutation is always available for this to be done manually - though in future there may be a desire to do some cache expiry with callbacks/timeouts etc if there's a need for it.

Does that work for you?

**Comment by staaam** [comment]
Worth noting that `data` element is optional (`A “relationship object” must contain at least one of the following: links, data, meta`), so in that case ids won't be available. But that doesn't matter, your cases are valid as well.

In any case, your proposed solution looks good for me. But you're still need to choose the default behavior :)

Another point worth considering regarding this behavior - whether it should be same behavior in action (dispatch..then) and in getter. The first thought - in case of action, you'd expect to get the object exactly as requested, with only requested fields/includes (which is `replace` strategy in your proposal), while using getter one might expect getting all existing data for the object (`update` strategy) - since there might not be direct connection between the request and data retrieval.
