### ISSUE TITLE
Unable to resubmit with data returned from action

### ISSUE THREAD

**Issue by mhluska** [mrichar1/jsonapi-vuex#50]
When an action is currently dispatched, the data returned has the jv helpers added via `addJvHelpers`. This returned data is then not possible to reuse in subsequent requests _in a modified form_ because the library checks for the presence of the `attrs` getter to determine if the data is user-submitted in `normToJsonApiItem`:

```
  // User-generated data (e.g. post) has no helper methods
  if (data[jvtag].hasOwnProperty('attrs') && jvConfig.followRelationshipsData) {
    jsonapi['attributes'] = data[jvtag].attrs
  } else {
    jsonapi['attributes'] = Object.assign({}, data)
    delete jsonapi['attributes'][jvtag]
  }
```

My current workaround is to strip the jv helpers before reusing the data in a subsequent post/patch.

Perhaps we could use a different kind of check for user-generated data since sometimes user-generated data might actually include the helpers?

**Comment by mrichar1** [comment]
I'm not entirely sure what the problem is here... 

`attrs` and `rels` are both dynamic `getters`. Specifically, `attrs` just checks for keys that are in the object root that *aren't* in _jv/relationships.

So if you modify the object to add/remove attributes to the root, `attrs` will return an 'updated' list.

If the helpers aren't present, it can't do this filtering, so it just has to trust that everything in the root (excluding `_jv`) is an attribute.

what am I missing?

**Comment by mhluska** [comment]
@mrichar1 I guess my issue here is somwhat similar to the [one about circular reference](https://github.com/mrichar1/jsonapi-vuex/issues/49#issuecomment-480049901).

```js
// `data._jv.attrs is undefined
const result = await store.dispatch('jv/patch', data);

// `result._jv.attrs is defined! Affects the logic in normToJsonApiItem
const secondResult = await store.dispatch('jv/patch', result);
```

My question is the same as in the other issue: does this library support using the return value of an action for subsequent actions? Seems like the calls are not really idempotent unless I manually strip some of the stuff the library adds onto the data.

**Comment by mrichar1** [comment]
OK - having looked again at #49 and this issue there must be a bug in `normToJsonapi` - since all methods call this to turn normalised data into JSONAPI data, and the end-result should have no circular references in it - something must be going wrong.

This function should be throwing away `_jv` but it must be slipping through the net somehow (as the only place we use circular refs) - I'll look at debugging this and coming up with a fix later today hopefully.
