### ISSUE TITLE
jvtag is not overridable

### ISSUE THREAD

**Issue by aselivanov** [mrichar1/jsonapi-vuex#76]
Looks like we really cannot use a custom tag (other than `_jv`) because of this early assignment:
https://github.com/mrichar1/jsonapi-vuex/blob/563c86421dec8d45963d1dcfe7418cdd24f9da97/src/jsonapi-vuex.js#L39

**Comment by mrichar1** [comment]
This *should* be a reference to the key in the `jvConfig` object, so provided that value is changed early enough in the config object, it should just work.

Given that the config object is overridden right at the start of instantiating the module, this shouldn't be a problem:

https://github.com/mrichar1/jsonapi-vuex/blob/master/src/jsonapi-vuex.js#L404-L405

Are you seeing issues actually redefining this tag? If so, can you paste your code where you import the module/pass in new config?

**Comment by aselivanov** [comment]
The `const jvtag` is initialized before config logic.

**Comment by aselivanov** [comment]
@mrichar1 Maybe this way? https://github.com/mrichar1/jsonapi-vuex/pull/77/files

**Comment by mrichar1** [comment]
Yes - sorry, I wasn't paying attention - I was thinking that: `const jvtag = jvConfig['jvtag']` would always be a reference to whatever the value of jvconfig['jvtag']` was - when in fact since this is a string it is copied and is then unchanged when `jvConfig` changes.

Have taken your PR in 77 and created a new PR (including some fixes for the test suite that this change requires). I'll merge this in shortly and make a new release.
